version: "3.8"

services:
  db:
    image: postgres:15
    container_name: tellform-postgres
    restart: always
    environment:
      POSTGRES_USER: kshitij
      POSTGRES_PASSWORD: bhardwaj
      POSTGRES_DB: tellform
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: